import Head from 'next/head'
import Image from 'next/image';
import Footer from '../components/Footer';
import NavBar from '../components/NavBar';
import favicon from '../public/favicon.ico';

export default function Home() {

  let card = []
  for (let i = 1; i <= 39; i++) {
    card.push(
      <div className='flex flex-col items-center mx-24 my-5' key={i}>
        <div className='w-56 bg-gradient-to-r from-cyan-500 to-blue-500 px-5 py-5 h-56 flex rounded-3xl hover:px-0 hover:py-0 transition duration-1000'>
          <Image alt='talk' width={"400px"} height="200px" src="/img/home/card_one.jpg" className='rounded-3xl'>
          </Image>
        </div>
        <p className='my-2'>Lorem mmm</p>
        <p className='w-40 text-sm my-2'>Lorem accusantium default accusantium ab</p>
        <div className='w-11/12 h-1 bg-cyan-700 rounded-3xl'></div>
      </div>
    )
  }

  return (
    <div>
      <Head>
        <title>Surveys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href={favicon.src} type="image/x-icon" />
      </Head>

      <main>
        <div className='bg-gradient-to-t from-indigo-500 via-purple-500 to-pink-500 w-screen h-screen'>
          <NavBar />

          <div className='text-center flex mx-auto w-5/6 justify-center my-56 font-bold'>
            <h2 className='font-sans text-white text-8xl w-4/6'>The Best Web Site of Surveys</h2>
          </div>
        </div>

        <div className='bg-white h-[30rem] flex justify-around'>
          <div className='my-auto'>
            <p className='text-[#395173] text-4xl mb-5 font-bold'>Features</p>
            <p className='text-sm w-96 text-zinc-600'>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commod.</p>
          </div>
          <div className='my-auto'>
            <div className='bg-[#395173] w-[40rem] h-96 p-8 flex'>
              <Image alt='surveys' width={"1920px"} height={"1272px"} src="/img/home/section.jpg" />
            </div>
          </div>
        </div>

        <div className='w-full h-1 bg-cyan-400'></div>

        <div className='mt-20'>
          <div className='flex flex-col'>
            <p className='text-[#395173] text-4xl mb-5 font-bold ml-28'>Talk Newest</p>
            <div className='w-full flex flex-wrap'>
              {
                card
              }
            </div>

          </div>
        </div>
      </main>

      <Footer/>
    </div>
  )
}
