import Head from 'next/head'
import favicon from '../public/favicon.ico';

export default function Home() {
  return (
    <div className='bg-gradient-to-t from-indigo-500 via-purple-500 to-pink-500 w-screen h-screen'>
      <Head>
        <title>Surveys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href={favicon.src} type="image/x-icon" />
      </Head>

      <main>
        
      </main>

      <footer>
      </footer>
    </div>
  )
}
