import Head from 'next/head'
import AdminBar from '../../components/AdminBar'
import favicon from '../../public/favicon.ico';

const DashBoard = () => {
  return (
    <>
    <Head>
        <title>Dash Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href={favicon.src} type="image/x-icon" />
      </Head>
    <div>
      <AdminBar/>
    </div>
    </>
  )
}

export default DashBoard